### ISSUE TITLE
Verwarring over uitklapicoon

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/urireferencer_dojo#5]
Het pijltje om een stuk uit te klappen lijkt soms eerder vast te hangen aan de bovenliggende blok. Momenteel lijkt het icoon voor bv. Adviezen eerder bij Dossiers te horen. Kan het design hier een beetje aangepast worden?

![image](https://cloud.githubusercontent.com/assets/676018/17621405/61df3882-6093-11e6-9a54-5fddb62a183d.png)

/cc @cahytinne @sophiemortier

**Comment by taeymma** [comment]
Waar doet zich dit precies voor? Op dev-besluiten staan die pijltjes goed bij mij in FF.

**Comment by taeymma** [comment]
Dit lijkt me enkel voor te komen bij actoren. Ik zal daar bugfix pushen.
